/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 statue.gltf --transform 
Files: statue.gltf [15.24MB] > statue-transformed.glb [1.9MB] (88%)
Author: Gravity Jack (https://sketchfab.com/gravityjack)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/statue-of-liberty-84094e8d5e724b5c882cf576ca12e44e
Title: Statue Of Liberty
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/statue-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Statue_Liberty_MAT_0.geometry} material={materials.Liberty_MAT} />
      <mesh geometry={nodes.Statue_RobesMAT_0.geometry} material={materials.RobesMAT} />
    </group>
  )
}

useGLTF.preload('/statue-transformed.glb')
